#! /usr/bin/env python
import experiments.cluster as cluster
import sys

# Usage: ./taccpy jobOutputFile train.py ...

j, expDir = cluster.getEnv()

args = sys.argv[2:]

if not '--path' in args: 
    args.append('--path')
    args.append(expDir)

j.setArgs(' '.join(args))
j.setOutputPrefix('%s/results/%s'%(expDir,sys.argv[1]))
j.submit()
